# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lifeexpect <- function(gamv) {
    .Call(`_pkgsolveOLG_lifeexpect`, gamv)
}

solveOLG_ <- function(starttime, maxiter, tol, damping_budget, damping_assets, damping_ab, damping_r, damping_new_assets, nthrds, dataOLGin) {
    .Call(`_pkgsolveOLG_solveOLG_`, starttime, maxiter, tol, damping_budget, damping_assets, damping_ab, damping_r, damping_new_assets, nthrds, dataOLGin)
}

coh2per <- function(inmat) {
    .Call(`_pkgsolveOLG_coh2per`, inmat)
}

aggcoh2per <- function(inmat) {
    .Call(`_pkgsolveOLG_aggcoh2per`, inmat)
}

per2coh <- function(inmat) {
    .Call(`_pkgsolveOLG_per2coh`, inmat)
}

fixeddim <- function() {
    .Call(`_pkgsolveOLG_fixeddim`)
}

